### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by leandrobh3** [mundipagg/MundiAPI-JAVA#1]
Boa noite!
Este repositório irá substituir o "mundipagg/mundipagg-one-java" ?
O que teremos de novidades?
Obrigado.

**Comment by matheusriboli** [comment]
Boa tarde Leandro.
Sim, esse repositório substituirá o mundipagg-one-java.
Esta sdk ainda está em beta, e é referente a nova api da Mundi.
Estamos validando algumas questões e em breve lançaremos a versão oficial da sdk.
Segue o link da documentação para mais informações:
https://docs.mundipagg.com/v1/reference
